export const WORLD_WIDTH = 5200;
export const WORLD_HEIGHT = 3200;

export const TERRAIN_OBSTACLES = Object.freeze([
  Object.freeze({ id: "north-divide", name: "Northern Divide", x: 2600, y: 840, width: 480, height: 880 }),
  Object.freeze({ id: "south-divide", name: "Southern Divide", x: 2600, y: 2360, width: 480, height: 880 }),
  Object.freeze({ id: "western-shelf", name: "Western Shelf", x: 1560, y: 2040, width: 640, height: 240 }),
  Object.freeze({ id: "eastern-shelf", name: "Eastern Shelf", x: 3640, y: 1160, width: 640, height: 240 }),
  Object.freeze({ id: "northwest-crags", name: "Northwest Crags", x: 1040, y: 600, width: 400, height: 320 }),
  Object.freeze({ id: "southeast-crags", name: "Southeast Crags", x: 4160, y: 2600, width: 400, height: 320 }),
  Object.freeze({
    id: "western-start-wall-north",
    name: "Western Start Wall",
    terrainType: "starting_wall",
    side: "player",
    x: 860,
    y: 1260,
    width: 360,
    height: 40,
  }),
  Object.freeze({
    id: "western-start-wall-front-north",
    name: "Western Start Wall",
    terrainType: "starting_wall",
    side: "player",
    x: 1060,
    y: 1400,
    width: 40,
    height: 240,
  }),
  Object.freeze({
    id: "western-start-wall-front-south",
    name: "Western Start Wall",
    terrainType: "starting_wall",
    side: "player",
    x: 1060,
    y: 1800,
    width: 40,
    height: 240,
  }),
  Object.freeze({
    id: "western-start-wall-south",
    name: "Western Start Wall",
    terrainType: "starting_wall",
    side: "player",
    x: 860,
    y: 1940,
    width: 360,
    height: 40,
  }),
  Object.freeze({
    id: "eastern-start-wall-north",
    name: "Eastern Start Wall",
    terrainType: "starting_wall",
    side: "enemy",
    x: 4340,
    y: 1260,
    width: 360,
    height: 40,
  }),
  Object.freeze({
    id: "eastern-start-wall-front-north",
    name: "Eastern Start Wall",
    terrainType: "starting_wall",
    side: "enemy",
    x: 4140,
    y: 1400,
    width: 40,
    height: 240,
  }),
  Object.freeze({
    id: "eastern-start-wall-front-south",
    name: "Eastern Start Wall",
    terrainType: "starting_wall",
    side: "enemy",
    x: 4140,
    y: 1800,
    width: 40,
    height: 240,
  }),
  Object.freeze({
    id: "eastern-start-wall-south",
    name: "Eastern Start Wall",
    terrainType: "starting_wall",
    side: "enemy",
    x: 4340,
    y: 1940,
    width: 360,
    height: 40,
  }),
]);

const SHARED_STARTS = Object.freeze({
  player: Object.freeze({
    generator: Object.freeze([600, 1600]),
    factory: Object.freeze([760, 1680]),
    mine: Object.freeze([760, 1440]),
    workers: Object.freeze([
      Object.freeze([680, 1640]),
      Object.freeze([680, 1720]),
      Object.freeze([760, 1800]),
    ]),
  }),
  enemy: Object.freeze({
    generator: Object.freeze([4600, 1600]),
    factory: Object.freeze([4440, 1680]),
    mine: Object.freeze([4440, 1440]),
    workers: Object.freeze([
      Object.freeze([4520, 1640]),
      Object.freeze([4520, 1720]),
      Object.freeze([4440, 1800]),
    ]),
  }),
});

function frozenRecords(records) {
  return Object.freeze(records.map((record) => Object.freeze(record)));
}

const BROKEN_FRONTIER_DEPOSITS = frozenRecords([
  { x: 900, y: 920 }, { x: 920, y: 2280 }, { x: 1320, y: 1440 },
  { x: 1360, y: 2600 }, { x: 1800, y: 720 }, { x: 1800, y: 1600 },
  { x: 1880, y: 2520 }, { x: 2200, y: 1480 }, { x: 3000, y: 1720 },
  { x: 3320, y: 680 }, { x: 3400, y: 1600 }, { x: 3320, y: 2520 },
  { x: 3880, y: 1440 }, { x: 4200, y: 920 }, { x: 4200, y: 2280 },
  { x: 2200, y: 240, remote: true, cluster: "Northern Frontier" },
  { x: 2400, y: 240, remote: true, cluster: "Northern Frontier" },
  { x: 2600, y: 240, remote: true, cluster: "Northern Frontier", rich: true, yieldMultiplier: 1.5 },
  { x: 2800, y: 240, remote: true, cluster: "Northern Frontier" },
  { x: 3000, y: 240, remote: true, cluster: "Northern Frontier" },
  { x: 2200, y: 2960, remote: true, cluster: "Southern Frontier" },
  { x: 2400, y: 2960, remote: true, cluster: "Southern Frontier" },
  { x: 2600, y: 2960, remote: true, cluster: "Southern Frontier", rich: true, yieldMultiplier: 1.5 },
  { x: 2800, y: 2960, remote: true, cluster: "Southern Frontier" },
  { x: 3000, y: 2960, remote: true, cluster: "Southern Frontier" },
]);

const ASHEN_DIVIDE_TERRAIN = frozenRecords([
  { id: "ashen-north-spine", name: "Ashen Spine", x: 2600, y: 480, width: 400, height: 560 },
  { id: "ashen-center-spine", name: "Ashen Spine", x: 2600, y: 1600, width: 400, height: 480 },
  { id: "ashen-south-spine", name: "Ashen Spine", x: 2600, y: 2720, width: 400, height: 560 },
  { id: "ashen-west-shelf", name: "Western Ash Shelf", x: 1580, y: 1040, width: 640, height: 200 },
  { id: "ashen-east-shelf", name: "Eastern Ash Shelf", x: 3620, y: 2160, width: 640, height: 200 },
  { id: "ashen-west-crags", name: "Western Ash Crags", x: 1540, y: 2460, width: 360, height: 360 },
  { id: "ashen-east-crags", name: "Eastern Ash Crags", x: 3660, y: 740, width: 360, height: 360 },
  { id: "ashen-northwest-basin", name: "Northwest Ash Basin", terrainType: "fracture", x: 1080, y: 400, width: 400, height: 160 },
  { id: "ashen-southwest-basin", name: "Southwest Ash Basin", terrainType: "fracture", x: 1080, y: 2800, width: 400, height: 160 },
  { id: "ashen-northeast-basin", name: "Northeast Ash Basin", terrainType: "fracture", x: 4120, y: 400, width: 400, height: 160 },
  { id: "ashen-southeast-basin", name: "Southeast Ash Basin", terrainType: "fracture", x: 4120, y: 2800, width: 400, height: 160 },
]);

const ASHEN_DIVIDE_DEPOSITS = frozenRecords([
  { x: 900, y: 800 }, { x: 900, y: 2400 }, { x: 1400, y: 1600 },
  { x: 1600, y: 600 }, { x: 1600, y: 2800 }, { x: 2050, y: 920 },
  { x: 2050, y: 2280 }, { x: 3150, y: 920 }, { x: 3150, y: 2280 },
  { x: 3600, y: 400 }, { x: 3600, y: 2600 }, { x: 3800, y: 1600 },
  { x: 4300, y: 800 }, { x: 4300, y: 2400 }, { x: 2600, y: 920 },
  { x: 2600, y: 2240 }, { x: 2600, y: 3120, remote: true, cluster: "Southern Ash Field", rich: true, yieldMultiplier: 1.5 },
]);

const IRON_CROSSINGS_TERRAIN = frozenRecords([
  { id: "cross-northwest", name: "Northwest Iron Mass", x: 2180, y: 1040, width: 400, height: 560 },
  { id: "cross-northeast", name: "Northeast Iron Mass", x: 3020, y: 1040, width: 400, height: 560 },
  { id: "cross-southwest", name: "Southwest Iron Mass", x: 2180, y: 2160, width: 400, height: 560 },
  { id: "cross-southeast", name: "Southeast Iron Mass", x: 3020, y: 2160, width: 400, height: 560 },
  { id: "cross-west-gate", name: "Western Gate Ridge", x: 1420, y: 1600, width: 240, height: 720 },
  { id: "cross-east-gate", name: "Eastern Gate Ridge", x: 3780, y: 1600, width: 240, height: 720 },
  { id: "cross-west-rim", name: "Western Rim", terrainType: "fracture", x: 1040, y: 1600, width: 160, height: 480 },
  { id: "cross-east-rim", name: "Eastern Rim", terrainType: "fracture", x: 4160, y: 1600, width: 160, height: 480 },
  { id: "cross-north-rim", name: "Northern Rim", terrainType: "fracture", x: 2600, y: 240, width: 720, height: 120 },
  { id: "cross-south-rim", name: "Southern Rim", terrainType: "fracture", x: 2600, y: 2960, width: 720, height: 120 },
  { id: "cross-northwest-outcrop", name: "Northwest Outcrop", x: 1000, y: 400, width: 320, height: 160 },
  { id: "cross-southwest-outcrop", name: "Southwest Outcrop", x: 1000, y: 2800, width: 320, height: 160 },
  { id: "cross-northeast-outcrop", name: "Northeast Outcrop", x: 4200, y: 400, width: 320, height: 160 },
  { id: "cross-southeast-outcrop", name: "Southeast Outcrop", x: 4200, y: 2800, width: 320, height: 160 },
]);

const IRON_CROSSINGS_DEPOSITS = frozenRecords([
  { x: 920, y: 760 }, { x: 920, y: 2440 }, { x: 1320, y: 960 },
  { x: 1320, y: 2240 }, { x: 1780, y: 480 }, { x: 1780, y: 2720 },
  { x: 1980, y: 1600 }, { x: 2380, y: 1600 }, { x: 2600, y: 480 },
  { x: 2600, y: 1600, remote: true, cluster: "Central Crossing", rich: true, yieldMultiplier: 1.5 }, { x: 2600, y: 2720 },
  { x: 2820, y: 1600 }, { x: 3220, y: 1600 }, { x: 3420, y: 480 },
  { x: 3420, y: 2720 }, { x: 3880, y: 960 }, { x: 3880, y: 2240 },
  { x: 4280, y: 760 }, { x: 4280, y: 2440 },
]);

const RUINED_MERIDIAN_TERRAIN = frozenRecords([
  { id: "meridian-north-wall", name: "Ancient Meridian", terrainType: "ruins", x: 2600, y: 480, width: 1040, height: 80 },
  { id: "meridian-south-wall", name: "Ancient Meridian", terrainType: "ruins", x: 2600, y: 2720, width: 1040, height: 80 },
  { id: "meridian-west-arch", name: "Western Ruin Arch", terrainType: "ruins", x: 2000, y: 1600, width: 80, height: 720 },
  { id: "meridian-east-arch", name: "Eastern Ruin Arch", terrainType: "ruins", x: 3200, y: 1600, width: 80, height: 720 },
  { id: "meridian-sanctum-north", name: "Broken Sanctum", terrainType: "ruins", x: 2600, y: 1200, width: 560, height: 80 },
  { id: "meridian-sanctum-south", name: "Broken Sanctum", terrainType: "ruins", x: 2600, y: 2000, width: 560, height: 80 },
  { id: "meridian-sanctum-west", name: "Broken Sanctum", terrainType: "ruins", x: 2320, y: 1600, width: 80, height: 320 },
  { id: "meridian-sanctum-east", name: "Broken Sanctum", terrainType: "ruins", x: 2880, y: 1600, width: 80, height: 320 },
  { id: "meridian-northwest-pillars", name: "Ancient Pillars", terrainType: "ruins", x: 1440, y: 800, width: 160, height: 320 },
  { id: "meridian-southwest-pillars", name: "Ancient Pillars", terrainType: "ruins", x: 1440, y: 2400, width: 160, height: 320 },
  { id: "meridian-northeast-pillars", name: "Ancient Pillars", terrainType: "ruins", x: 3760, y: 800, width: 160, height: 320 },
  { id: "meridian-southeast-pillars", name: "Ancient Pillars", terrainType: "ruins", x: 3760, y: 2400, width: 160, height: 320 },
]);

const RUINED_MERIDIAN_DEPOSITS = frozenRecords([
  { x: 960, y: 800 }, { x: 960, y: 2400 }, { x: 1320, y: 1600 },
  { x: 1720, y: 480 }, { x: 1720, y: 2720 }, { x: 2040, y: 920 },
  { x: 2040, y: 2280 }, { x: 2440, y: 800 }, { x: 2440, y: 2400 },
  { x: 2600, y: 1600, remote: true, cluster: "Sanctum Vault", rich: true, yieldMultiplier: 1.5 },
  { x: 2760, y: 800 }, { x: 2760, y: 2400 }, { x: 3160, y: 920 },
  { x: 3160, y: 2280 }, { x: 3480, y: 480 }, { x: 3480, y: 2720 },
  { x: 3880, y: 1600 }, { x: 4240, y: 800 }, { x: 4240, y: 2400 },
]);

const TWIN_CALDERAS_TERRAIN = frozenRecords([
  { id: "caldera-west-north", name: "Western Caldera", terrainType: "fracture", x: 1840, y: 920, width: 720, height: 160 },
  { id: "caldera-west-south", name: "Western Caldera", terrainType: "fracture", x: 1840, y: 2280, width: 720, height: 160 },
  { id: "caldera-west-rim", name: "Western Caldera", terrainType: "fracture", x: 1480, y: 1600, width: 160, height: 720 },
  { id: "caldera-west-inner", name: "Western Caldera", terrainType: "fracture", x: 2200, y: 1600, width: 160, height: 720 },
  { id: "caldera-east-north", name: "Eastern Caldera", terrainType: "fracture", x: 3360, y: 920, width: 720, height: 160 },
  { id: "caldera-east-south", name: "Eastern Caldera", terrainType: "fracture", x: 3360, y: 2280, width: 720, height: 160 },
  { id: "caldera-east-inner", name: "Eastern Caldera", terrainType: "fracture", x: 3000, y: 1600, width: 160, height: 720 },
  { id: "caldera-east-rim", name: "Eastern Caldera", terrainType: "fracture", x: 3720, y: 1600, width: 160, height: 720 },
  { id: "caldera-north-split", name: "Northern Fault", terrainType: "fracture", x: 2600, y: 440, width: 240, height: 560 },
  { id: "caldera-south-split", name: "Southern Fault", terrainType: "fracture", x: 2600, y: 2760, width: 240, height: 560 },
  { id: "caldera-northwest-spire", name: "Northwest Caldera Spire", terrainType: "fracture", x: 1000, y: 520, width: 240, height: 240 },
  { id: "caldera-southwest-spire", name: "Southwest Caldera Spire", terrainType: "fracture", x: 1000, y: 2680, width: 240, height: 240 },
  { id: "caldera-northeast-spire", name: "Northeast Caldera Spire", terrainType: "fracture", x: 4200, y: 520, width: 240, height: 240 },
  { id: "caldera-southeast-spire", name: "Southeast Caldera Spire", terrainType: "fracture", x: 4200, y: 2680, width: 240, height: 240 },
]);

const TWIN_CALDERAS_DEPOSITS = frozenRecords([
  { x: 920, y: 760 }, { x: 920, y: 2440 }, { x: 1240, y: 1120 },
  { x: 1240, y: 2080 }, { x: 1680, y: 1600, remote: true, cluster: "Western Basin" },
  { x: 1840, y: 560 }, { x: 1840, y: 2640 }, { x: 2360, y: 1040 },
  { x: 2360, y: 2160 }, { x: 2600, y: 1600, remote: true, cluster: "Caldera Core", rich: true, yieldMultiplier: 1.5 },
  { x: 2840, y: 1040 }, { x: 2840, y: 2160 }, { x: 3360, y: 560 },
  { x: 3360, y: 2640 }, { x: 3520, y: 1600, remote: true, cluster: "Eastern Basin" },
  { x: 3960, y: 1120 }, { x: 3960, y: 2080 }, { x: 4280, y: 760 },
  { x: 4280, y: 2440 },
]);

export const DEFAULT_MAP_ID = "broken_frontier";

export const MAP_DEFINITIONS = Object.freeze({
  broken_frontier: Object.freeze({
    id: "broken_frontier",
    name: "Broken Frontier",
    description: "Green frontier grasslands, fortified starting positions, central divides, and rich remote clusters.",
    theme: "grassland",
    width: WORLD_WIDTH,
    height: WORLD_HEIGHT,
    terrain: TERRAIN_OBSTACLES,
    starts: SHARED_STARTS,
    deposits: BROKEN_FRONTIER_DEPOSITS,
  }),
  ashen_divide: Object.freeze({
    id: "ashen_divide",
    name: "Ashen Divide",
    description: "A red apocalyptic ash field where a broken central spine creates two major attack lanes.",
    theme: "apocalypse",
    width: WORLD_WIDTH,
    height: WORLD_HEIGHT,
    terrain: ASHEN_DIVIDE_TERRAIN,
    starts: SHARED_STARTS,
    deposits: ASHEN_DIVIDE_DEPOSITS,
  }),
  iron_crossings: Object.freeze({
    id: "iron_crossings",
    name: "Iron Crossings",
    description: "Open green grasslands surround four rocky masses and their narrow crossroads.",
    theme: "grassland",
    width: WORLD_WIDTH,
    height: WORLD_HEIGHT,
    terrain: IRON_CROSSINGS_TERRAIN,
    starts: SHARED_STARTS,
    deposits: IRON_CROSSINGS_DEPOSITS,
  }),
  ruined_meridian: Object.freeze({
    id: "ruined_meridian",
    name: "Ruined Meridian",
    description: "Overgrown green fields, dense ancient walls, and shattered arches create close, twisting lanes.",
    theme: "grassland",
    width: WORLD_WIDTH,
    height: WORLD_HEIGHT,
    terrain: RUINED_MERIDIAN_TERRAIN,
    starts: SHARED_STARTS,
    deposits: RUINED_MERIDIAN_DEPOSITS,
  }),
  twin_calderas: Object.freeze({
    id: "twin_calderas",
    name: "Twin Calderas",
    description: "A red apocalyptic badland of enclosed basins and a fractured central pass.",
    theme: "apocalypse",
    width: WORLD_WIDTH,
    height: WORLD_HEIGHT,
    terrain: TWIN_CALDERAS_TERRAIN,
    starts: SHARED_STARTS,
    deposits: TWIN_CALDERAS_DEPOSITS,
  }),
});

export function resolveMatchMapId({
  matchMode = "singleplayer",
  selectedMapId = DEFAULT_MAP_ID,
  randomValue = 0,
} = {}) {
  const mapIds = Object.keys(MAP_DEFINITIONS);
  if (matchMode === "multiplayer") {
    const boundedRandom = Number.isFinite(randomValue)
      ? Math.min(Math.max(randomValue, 0), 1 - Number.EPSILON)
      : 0;
    return mapIds[Math.floor(boundedRandom * mapIds.length)];
  }
  return MAP_DEFINITIONS[selectedMapId] ? selectedMapId : DEFAULT_MAP_ID;
}

function provisionalFactoryUnit({ name, role, roleDescription, unitDomain, tier, ...stats }) {
  return {
    name,
    role,
    roleDescription,
    unitDomain,
    movementLayer: unitDomain === "air" ? "air" : "ground",
    tier,
    ...stats,
    metalValue: stats.metalCost,
    provisionalBalance: true,
  };
}

export const BUILD_DURATION_MULTIPLIER = 4;

const DEFAULT_PROJECTILE_KINETICS = Object.freeze({
  speed: 980,
  minimumTravelTime: 0.055,
});

const PROJECTILE_KINETICS_BY_ROLE = Object.freeze({
  mortar: Object.freeze({ speed: 340, minimumTravelTime: 0.28 }),
  arsenal_colossus: Object.freeze({ speed: 760, minimumTravelTime: 0.1 }),
  hexapod_landship: Object.freeze({ speed: 520, minimumTravelTime: 0.14 }),
  artillery: Object.freeze({ speed: 420, minimumTravelTime: 0.16 }),
  bomber: Object.freeze({ speed: 420, minimumTravelTime: 0.16 }),
  tank: Object.freeze({ speed: 680, minimumTravelTime: 0.09 }),
  bulwark: Object.freeze({ speed: 680, minimumTravelTime: 0.09 }),
});

export function projectileKinetics(definition) {
  if (!definition || definition.attackDamage <= 0 || definition.instantHit) return null;
  const roleKinetics = PROJECTILE_KINETICS_BY_ROLE[definition.role] ||
    DEFAULT_PROJECTILE_KINETICS;
  return {
    speed: definition.projectileSpeed || roleKinetics.speed,
    minimumTravelTime:
      definition.minimumProjectileTravelTime ?? roleKinetics.minimumTravelTime,
  };
}

const FACTORY_UNIT_DEFINITIONS = Object.freeze({
  scout_vehicle: provisionalFactoryUnit({
    name: "Tier 1 Scout Vehicle", role: "vehicle_scout", roleDescription: "Fast ground reconnaissance",
    unitDomain: "vehicle", tier: 1, radius: 12, maxHp: 135, maxEnergy: 660, speed: 108,
    movementEnergyPerUnit: 0.05, attackRange: 120, attackDamage: 11, attackEnergy: 5,
    attackCooldown: 0.65, metalCost: 80, productionTime: 6, supplyCost: 3,
  }),
  scout_vehicle_t2: provisionalFactoryUnit({
    name: "Tier 2 Scout Vehicle", role: "vehicle_scout", roleDescription: "Fast ground reconnaissance",
    unitDomain: "vehicle", tier: 2, radius: 13, maxHp: 190, maxEnergy: 900, speed: 116,
    movementEnergyPerUnit: 0.045, attackRange: 135, attackDamage: 16, attackEnergy: 6,
    attackCooldown: 0.58, metalCost: 125, productionTime: 7.5, supplyCost: 5,
  }),
  scout_vehicle_t3: provisionalFactoryUnit({
    name: "Tier 3 Scout Vehicle", role: "vehicle_scout", roleDescription: "Fast ground reconnaissance",
    unitDomain: "vehicle", tier: 3, radius: 14, maxHp: 260, maxEnergy: 1200, speed: 125,
    movementEnergyPerUnit: 0.04, attackRange: 150, attackDamage: 22, attackEnergy: 7,
    attackCooldown: 0.5, metalCost: 180, productionTime: 9, supplyCost: 7,
  }),
  radar_vehicle: provisionalFactoryUnit({
    name: "Tier 1 Pathfinder Radar", role: "radar_vehicle",
    roleDescription: "Mobile long-range radar with one light defensive cannon",
    unitDomain: "vehicle", tier: 1, radius: 12, maxHp: 145, maxEnergy: 840, speed: 82,
    movementEnergyPerUnit: 0.055, attackRange: 145, attackDamage: 7, attackEnergy: 5,
    attackCooldown: 0.8, visionRange: 700, radarRange: 700,
    metalCost: 125, productionTime: 9, supplyCost: 5, additionalWeaponHardpoints: 0,
  }),
  radar_vehicle_t2: provisionalFactoryUnit({
    name: "Tier 2 Pathfinder Radar", role: "radar_vehicle",
    roleDescription: "Mobile long-range radar with one light defensive cannon",
    unitDomain: "vehicle", tier: 2, radius: 13, maxHp: 205, maxEnergy: 1140, speed: 88,
    movementEnergyPerUnit: 0.05, attackRange: 165, attackDamage: 10, attackEnergy: 6,
    attackCooldown: 0.72, visionRange: 850, radarRange: 850,
    metalCost: 195, productionTime: 11, supplyCost: 8, additionalWeaponHardpoints: 0,
  }),
  radar_vehicle_t3: provisionalFactoryUnit({
    name: "Tier 3 Pathfinder Radar", role: "radar_vehicle",
    roleDescription: "Mobile long-range radar with one light defensive cannon",
    unitDomain: "vehicle", tier: 3, radius: 14, maxHp: 285, maxEnergy: 1500, speed: 95,
    movementEnergyPerUnit: 0.045, attackRange: 185, attackDamage: 14, attackEnergy: 8,
    attackCooldown: 0.64, visionRange: 1000, radarRange: 1000,
    metalCost: 290, productionTime: 14, supplyCost: 11, additionalWeaponHardpoints: 0,
  }),
  battle_tank: provisionalFactoryUnit({
    name: "Tier 1 Battle Tank", role: "tank", roleDescription: "Armored direct-fire combat",
    unitDomain: "vehicle", tier: 1, radius: 15, maxHp: 310, maxEnergy: 840, speed: 58,
    movementEnergyPerUnit: 0.07, attackRange: 145, attackDamage: 30, attackEnergy: 12,
    attackCooldown: 1.4, metalCost: 180, productionTime: 12, supplyCost: 9,
  }),
  battle_tank_t2: provisionalFactoryUnit({
    name: "Tier 2 Battle Tank", role: "tank", roleDescription: "Armored direct-fire combat",
    unitDomain: "vehicle", tier: 2, radius: 16, maxHp: 440, maxEnergy: 1140, speed: 62,
    movementEnergyPerUnit: 0.064, attackRange: 160, attackDamage: 43, attackEnergy: 14,
    attackCooldown: 1.28, metalCost: 275, productionTime: 14.5, supplyCost: 13,
  }),
  battle_tank_t3: provisionalFactoryUnit({
    name: "Tier 3 Battle Tank", role: "tank", roleDescription: "Armored direct-fire combat",
    unitDomain: "vehicle", tier: 3, radius: 17, maxHp: 610, maxEnergy: 1500, speed: 66,
    movementEnergyPerUnit: 0.058, attackRange: 175, attackDamage: 59, attackEnergy: 17,
    attackCooldown: 1.15, metalCost: 410, productionTime: 18, supplyCost: 18,
  }),
  mobile_artillery: provisionalFactoryUnit({
    name: "Tier 1 Mobile Artillery", role: "artillery", roleDescription: "Long-range fire support",
    unitDomain: "vehicle", tier: 1, radius: 13, maxHp: 135, maxEnergy: 780, speed: 54,
    movementEnergyPerUnit: 0.06, minimumAttackRange: 160, attackRange: 400,
    attackDamage: 40, attackEnergy: 16,
    attackCooldown: 2.2, metalCost: 170, productionTime: 13, supplyCost: 7,
  }),
  mobile_artillery_t2: provisionalFactoryUnit({
    name: "Tier 2 Mobile Artillery", role: "artillery", roleDescription: "Long-range fire support",
    unitDomain: "vehicle", tier: 2, radius: 14, maxHp: 195, maxEnergy: 1080, speed: 58,
    movementEnergyPerUnit: 0.055, minimumAttackRange: 180, attackRange: 480,
    attackDamage: 57, attackEnergy: 19,
    attackCooldown: 2, metalCost: 260, productionTime: 15.5, supplyCost: 11,
  }),
  mobile_artillery_t3: provisionalFactoryUnit({
    name: "Tier 3 Mobile Artillery", role: "artillery", roleDescription: "Long-range fire support",
    unitDomain: "vehicle", tier: 3, radius: 15, maxHp: 275, maxEnergy: 1440, speed: 62,
    movementEnergyPerUnit: 0.05, minimumAttackRange: 200, attackRange: 560,
    attackDamage: 78, attackEnergy: 23,
    attackCooldown: 1.8, metalCost: 390, productionTime: 19, supplyCost: 15,
  }),
  grid_tanker: provisionalFactoryUnit({
    name: "Tier 1 Grid Tanker", role: "grid_tanker", roleDescription: "Armed mobile energy support",
    unitDomain: "vehicle", tier: 1, radius: 13, maxHp: 190, maxEnergy: 3000, speed: 70,
    movementEnergyPerUnit: 0.045, attackRange: 135, attackDamage: 5, attackEnergy: 4,
    attackCooldown: 0.86, metalCost: 140, productionTime: 10, supplyCost: 6,
    transferRange: 100, transferRate: 32, protectedReserve: 80,
  }),
  grid_tanker_t2: provisionalFactoryUnit({
    name: "Tier 2 Grid Tanker", role: "grid_tanker", roleDescription: "Armed mobile energy support",
    unitDomain: "vehicle", tier: 2, radius: 14, maxHp: 275, maxEnergy: 4200, speed: 75,
    movementEnergyPerUnit: 0.04, attackRange: 150, attackDamage: 8, attackEnergy: 5,
    attackCooldown: 0.78, metalCost: 210, productionTime: 13, supplyCost: 9,
    transferRange: 120, transferRate: 48, protectedReserve: 110,
  }),
  grid_tanker_t3: provisionalFactoryUnit({
    name: "Tier 3 Grid Tanker", role: "grid_tanker", roleDescription: "Armed mobile energy support",
    unitDomain: "vehicle", tier: 3, radius: 15, maxHp: 380, maxEnergy: 6000, speed: 80,
    movementEnergyPerUnit: 0.036, attackRange: 170, attackDamage: 11, attackEnergy: 7,
    attackCooldown: 0.7, metalCost: 310, productionTime: 16, supplyCost: 13,
    transferRange: 145, transferRate: 68, protectedReserve: 150,
  }),
  flak_crawler: provisionalFactoryUnit({
    name: "Tier 1 Flak Crawler", role: "anti_air_vehicle",
    roleDescription: "Mobile anti-air battery · 2× damage against aircraft",
    unitDomain: "vehicle", tier: 1, radius: 12, maxHp: 150, maxEnergy: 720, speed: 76,
    movementEnergyPerUnit: 0.055, attackRange: 210, attackDamage: 9, attackEnergy: 6,
    attackCooldown: 0.42, metalCost: 130, productionTime: 9, supplyCost: 6,
    airDamageMultiplier: 2, preferredTargetLayer: "air",
  }),
  flak_crawler_t2: provisionalFactoryUnit({
    name: "Tier 2 Flak Crawler", role: "anti_air_vehicle",
    roleDescription: "Mobile anti-air battery · 2× damage against aircraft",
    unitDomain: "vehicle", tier: 2, radius: 13, maxHp: 215, maxEnergy: 990, speed: 82,
    movementEnergyPerUnit: 0.05, attackRange: 240, attackDamage: 13, attackEnergy: 7,
    attackCooldown: 0.37, metalCost: 200, productionTime: 11, supplyCost: 9,
    airDamageMultiplier: 2, preferredTargetLayer: "air",
  }),
  flak_crawler_t3: provisionalFactoryUnit({
    name: "Tier 3 Flak Crawler", role: "anti_air_vehicle",
    roleDescription: "Mobile anti-air battery · 2× damage against aircraft",
    unitDomain: "vehicle", tier: 3, radius: 14, maxHp: 300, maxEnergy: 1320, speed: 88,
    movementEnergyPerUnit: 0.045, attackRange: 275, attackDamage: 18, attackEnergy: 9,
    attackCooldown: 0.32, metalCost: 300, productionTime: 14, supplyCost: 13,
    airDamageMultiplier: 2, preferredTargetLayer: "air",
  }),
  interceptor_t2: provisionalFactoryUnit({
    name: "Tier 2 Interceptor", role: "interceptor", roleDescription: "Air-superiority fighter",
    unitDomain: "air", tier: 2, radius: 9, maxHp: 105, maxEnergy: 900, speed: 270,
    movementEnergyPerUnit: 0.08, attackRange: 155, attackDamage: 18, attackEnergy: 8,
    attackCooldown: 0.55, metalCost: 150, productionTime: 8, supplyCost: 5,
    airDamageMultiplier: 2, groundDamageMultiplier: 0.5, preferredTargetLayer: "air",
  }),
  interceptor_t3: provisionalFactoryUnit({
    name: "Tier 3 Interceptor", role: "interceptor", roleDescription: "Air-superiority fighter",
    unitDomain: "air", tier: 3, radius: 10, maxHp: 150, maxEnergy: 1260, speed: 300,
    movementEnergyPerUnit: 0.072, attackRange: 175, attackDamage: 26, attackEnergy: 10,
    attackCooldown: 0.46, metalCost: 225, productionTime: 10, supplyCost: 7,
    airDamageMultiplier: 2, groundDamageMultiplier: 0.5, preferredTargetLayer: "air",
  }),
  gunship_t2: provisionalFactoryUnit({
    name: "Tier 2 Gunship", role: "gunship", roleDescription: "Durable aerial assault",
    unitDomain: "air", tier: 2, radius: 12, maxHp: 205, maxEnergy: 1140, speed: 185,
    movementEnergyPerUnit: 0.095, attackRange: 175, attackDamage: 25, attackEnergy: 11,
    attackCooldown: 0.82, metalCost: 240, productionTime: 13, supplyCost: 9,
  }),
  gunship_t3: provisionalFactoryUnit({
    name: "Tier 3 Gunship", role: "gunship", roleDescription: "Durable aerial assault",
    unitDomain: "air", tier: 3, radius: 13, maxHp: 295, maxEnergy: 1560, speed: 205,
    movementEnergyPerUnit: 0.086, attackRange: 200, attackDamage: 36, attackEnergy: 14,
    attackCooldown: 0.7, metalCost: 360, productionTime: 16, supplyCost: 13,
  }),
  bomber_t2: provisionalFactoryUnit({
    name: "Tier 2 Bomber", role: "bomber", roleDescription: "Heavy aerial strike",
    unitDomain: "air", tier: 2, radius: 13, maxHp: 170, maxEnergy: 1320, speed: 160,
    movementEnergyPerUnit: 0.11, attackRange: 190, attackDamage: 56, attackEnergy: 22,
    attackCooldown: 2.3, metalCost: 285, productionTime: 15, supplyCost: 11,
  }),
  bomber_t3: provisionalFactoryUnit({
    name: "Tier 3 Bomber", role: "bomber", roleDescription: "Heavy aerial strike",
    unitDomain: "air", tier: 3, radius: 13, maxHp: 245, maxEnergy: 1800, speed: 175,
    movementEnergyPerUnit: 0.1, attackRange: 215, attackDamage: 82, attackEnergy: 28,
    attackCooldown: 2.05, metalCost: 430, productionTime: 19, supplyCost: 16,
  }),
  energy_tender_t2: provisionalFactoryUnit({
    name: "Tier 2 Energy Tender", role: "energy_tender", roleDescription: "Armed airborne energy support",
    unitDomain: "air", tier: 2, radius: 11, maxHp: 130, maxEnergy: 3900, speed: 210,
    movementEnergyPerUnit: 0.085, attackRange: 155, attackDamage: 6, attackEnergy: 5,
    attackCooldown: 0.8, metalCost: 220, productionTime: 12, supplyCost: 8,
    transferRange: 125, transferRate: 45, protectedReserve: 100,
  }),
  energy_tender_t3: provisionalFactoryUnit({
    name: "Tier 3 Energy Tender", role: "energy_tender", roleDescription: "Armed airborne energy support",
    unitDomain: "air", tier: 3, radius: 12, maxHp: 190, maxEnergy: 5700, speed: 235,
    movementEnergyPerUnit: 0.075, attackRange: 175, attackDamage: 9, attackEnergy: 7,
    attackCooldown: 0.7, metalCost: 330, productionTime: 15, supplyCost: 11,
    transferRange: 150, transferRate: 65, protectedReserve: 140,
  }),
  dropship_t2: provisionalFactoryUnit({
    name: "Tier 2 Dropship", role: "transport", roleDescription: "Air transport · carries 8 ground units",
    unitDomain: "air", tier: 2, radius: 13, maxHp: 240, maxEnergy: 2100, speed: 195,
    movementEnergyPerUnit: 0.082, attackRange: 0, attackDamage: 0, attackEnergy: 0,
    attackCooldown: 0, metalCost: 290, productionTime: 15, supplyCost: 12,
    transportCapacity: 8, transportLoadRange: 12,
  }),
  dropship_t3: provisionalFactoryUnit({
    name: "Tier 3 Dropship", role: "transport", roleDescription: "Air transport · carries 8 ground units",
    unitDomain: "air", tier: 3, radius: 13, maxHp: 340, maxEnergy: 3000, speed: 220,
    movementEnergyPerUnit: 0.074, attackRange: 0, attackDamage: 0, attackEnergy: 0,
    attackCooldown: 0, metalCost: 430, productionTime: 19, supplyCost: 17,
    transportCapacity: 8, transportLoadRange: 12,
  }),
  radar_aircraft_t2: provisionalFactoryUnit({
    name: "Tier 2 Skywatch Radar", role: "radar_aircraft",
    roleDescription: "Fast airborne radar with one light defensive gun",
    unitDomain: "air", tier: 2, radius: 10, maxHp: 115, maxEnergy: 1080, speed: 235,
    movementEnergyPerUnit: 0.082, attackRange: 175, attackDamage: 7, attackEnergy: 6,
    attackCooldown: 0.72, visionRange: 900, radarRange: 900,
    metalCost: 195, productionTime: 10, supplyCost: 7, additionalWeaponHardpoints: 0,
  }),
  radar_aircraft_t3: provisionalFactoryUnit({
    name: "Tier 3 Skywatch Radar", role: "radar_aircraft",
    roleDescription: "Fast airborne radar with one light defensive gun",
    unitDomain: "air", tier: 3, radius: 11, maxHp: 165, maxEnergy: 1470, speed: 260,
    movementEnergyPerUnit: 0.074, attackRange: 205, attackDamage: 11, attackEnergy: 8,
    attackCooldown: 0.64, visionRange: 1100, radarRange: 1100,
    metalCost: 295, productionTime: 13, supplyCost: 10, additionalWeaponHardpoints: 0,
  }),
  arsenal_colossus: provisionalFactoryUnit({
    name: "Arsenal Colossus", role: "arsenal_colossus",
    roleDescription: "Huge multi-weapon experimental assault mech",
    unitDomain: "experimental", tier: 3, radius: 30, maxHp: 2200, maxEnergy: 6000,
    speed: 42, movementEnergyPerUnit: 0.12, attackRange: 290, attackDamage: 180,
    attackEnergy: 58, attackCooldown: 1.15, metalCost: 1800, productionTime: 48,
    supplyCost: 70, weaponCount: 8, salvoCount: 5, structureDamageMultiplier: 1.2,
  }),
  hexapod_landship: provisionalFactoryUnit({
    name: "Hexapod Landship", role: "hexapod_landship",
    roleDescription: "Six-legged walking battleship with three independently targeting cannons",
    unitDomain: "experimental", tier: 3, radius: 44, maxHp: 4200, maxEnergy: 7800,
    speed: 25, movementEnergyPerUnit: 0.16, attackRange: 370, attackDamage: 310,
    attackEnergy: 95, attackCooldown: 2.5, metalCost: 3000, productionTime: 72,
    supplyCost: 120, legCount: 6, stridesOverStructures: true, weaponCount: 3,
    salvoCount: 1, projectileSpeed: 520, minimumProjectileTravelTime: 0.14,
    structureDamageMultiplier: 1.6,
    weaponSystems: Object.freeze([
      Object.freeze({ id: "main", name: "Main Siege Cannon", attackRange: 370, attackDamage: 140, attackEnergy: 43, attackCooldown: 2.7 }),
      Object.freeze({ id: "port", name: "Port Cannon", attackRange: 330, attackDamage: 85, attackEnergy: 26, attackCooldown: 2.2 }),
      Object.freeze({ id: "starboard", name: "Starboard Cannon", attackRange: 330, attackDamage: 85, attackEnergy: 26, attackCooldown: 2.2 }),
    ]),
  }),
  zenith_doughnut: provisionalFactoryUnit({
    name: "Zenith Doughnut", role: "zenith_doughnut",
    roleDescription: "Toroidal ground-beam aircraft with twin dorsal anti-air batteries",
    unitDomain: "air", tier: 3, radius: 72, maxHp: 2100, maxEnergy: 7200,
    speed: 375, movementEnergyPerUnit: 0.14, attackRange: 0, attackDamage: 0,
    attackEnergy: 0, attackCooldown: 0, metalCost: 2500, productionTime: 62,
    supplyCost: 95, groundAttackOnly: true, underbellyBeamRadius: 48,
    underbellyBeamDamagePerSecond: 150, underbellyBeamEnergyPerSecond: 38,
    automaticallyPursuesBeamTargets: true, automaticTargetAcquisitionRange: 400,
    weaponSystems: Object.freeze([
      Object.freeze({
        id: "port_aa", name: "Port Dorsal AA Battery", targetLayer: "air",
        attackRange: 340, attackDamage: 18, attackEnergy: 9, attackCooldown: 0.45,
        airDamageMultiplier: 2, projectileSpeed: 1050,
        minimumProjectileTravelTime: 0.07, projectileTracksTarget: true,
      }),
      Object.freeze({
        id: "starboard_aa", name: "Starboard Dorsal AA Battery", targetLayer: "air",
        attackRange: 340, attackDamage: 18, attackEnergy: 9, attackCooldown: 0.45,
        airDamageMultiplier: 2, projectileSpeed: 1050,
        minimumProjectileTravelTime: 0.07, projectileTracksTarget: true,
      }),
    ]),
  }),
});

const baseUnitDefinitions = {
  worker_drone_t1: {
    name: "Tier 1 Worker Drone",
    role: "worker",
    roleDescription: "Construction, factory assistance, allied repair, and close-range self-defense",
    tier: 1,
    radius: 6,
    maxHp: 70,
    maxEnergy: 690,
    speed: 72,
    movementEnergyPerUnit: 0.035,
    attackRange: 55,
    attackDamage: 4,
    attackEnergy: 2,
    attackCooldown: 1.2,
    metalValue: 45,
    metalCost: 45,
    productionTime: 5,
    supplyCost: 1,
    workerTier: 1,
    buildRate: 1,
    productionAssistRate: 0.25,
    automaticRepairRange: 180,
    repairRange: 24,
    repairRate: 8,
    repairEnergyPerHp: 0.5,
    provisionalBalance: true,
  },
  worker_drone_t2: {
    name: "Tier 2 Worker Drone",
    role: "worker",
    roleDescription: "Construction, factory assistance, allied repair, and close-range self-defense",
    tier: 2,
    radius: 7,
    maxHp: 95,
    maxEnergy: 990,
    speed: 78,
    movementEnergyPerUnit: 0.03,
    attackRange: 60,
    attackDamage: 5,
    attackEnergy: 2.5,
    attackCooldown: 1.1,
    metalValue: 75,
    metalCost: 75,
    productionTime: 5,
    supplyCost: 2,
    workerTier: 2,
    buildRate: 1.65,
    productionAssistRate: 0.4,
    automaticRepairRange: 180,
    repairRange: 26,
    repairRate: 13,
    repairEnergyPerHp: 0.5,
    provisionalBalance: true,
  },
  worker_drone_t3: {
    name: "Tier 3 Worker Drone",
    role: "worker",
    roleDescription: "Construction, factory assistance, allied repair, and close-range self-defense",
    tier: 3,
    radius: 8,
    maxHp: 125,
    maxEnergy: 1380,
    speed: 84,
    movementEnergyPerUnit: 0.026,
    attackRange: 65,
    attackDamage: 6,
    attackEnergy: 3,
    attackCooldown: 1,
    metalValue: 120,
    metalCost: 120,
    productionTime: 5,
    supplyCost: 3,
    workerTier: 3,
    buildRate: 2.6,
    productionAssistRate: 0.65,
    automaticRepairRange: 180,
    repairRange: 28,
    repairRate: 20,
    repairEnergyPerHp: 0.5,
    provisionalBalance: true,
  },
  scout_mech: {
    name: "Tier 1 Vanguard Mech",
    role: "vanguard",
    tier: 1,
    radius: 9,
    maxHp: 120,
    maxEnergy: 600,
    speed: 92,
    movementEnergyPerUnit: 0.055,
    attackRange: 125,
    attackDamage: 13,
    attackEnergy: 6,
    attackCooldown: 0.8,
    metalValue: 85,
    metalCost: 85,
    productionTime: 7,
    supplyCost: 4,
    provisionalBalance: true,
  },
  scout_mech_t2: {
    name: "Tier 2 Vanguard Mech",
    role: "vanguard",
    tier: 2,
    radius: 10,
    maxHp: 165,
    maxEnergy: 870,
    speed: 98,
    movementEnergyPerUnit: 0.05,
    attackRange: 135,
    attackDamage: 18,
    attackEnergy: 7,
    attackCooldown: 0.72,
    metalValue: 130,
    metalCost: 130,
    productionTime: 8.5,
    supplyCost: 6,
    provisionalBalance: true,
  },
  scout_mech_t3: {
    name: "Tier 3 Vanguard Mech",
    role: "vanguard",
    tier: 3,
    radius: 11,
    maxHp: 220,
    maxEnergy: 1200,
    speed: 105,
    movementEnergyPerUnit: 0.045,
    attackRange: 145,
    attackDamage: 24,
    attackEnergy: 8,
    attackCooldown: 0.64,
    metalValue: 190,
    metalCost: 190,
    productionTime: 10,
    supplyCost: 8,
    provisionalBalance: true,
  },
  assault_mech: {
    name: "Tier 1 Bulwark Mech",
    role: "bulwark",
    tier: 1,
    radius: 11,
    maxHp: 190,
    maxEnergy: 780,
    speed: 68,
    movementEnergyPerUnit: 0.07,
    attackRange: 150,
    attackDamage: 24,
    attackEnergy: 10,
    attackCooldown: 1.25,
    metalValue: 140,
    metalCost: 140,
    productionTime: 11,
    supplyCost: 8,
    abilities: {
      overdrive: {
        name: "Overdrive",
        energyCost: 30,
        duration: 6,
        speedMultiplier: 1.65,
        cooldownMultiplier: 0.65,
      },
    },
    provisionalBalance: true,
  },
  assault_mech_t2: {
    name: "Tier 2 Bulwark Mech",
    role: "bulwark",
    tier: 2,
    radius: 12,
    maxHp: 270,
    maxEnergy: 1080,
    speed: 72,
    movementEnergyPerUnit: 0.064,
    attackRange: 165,
    attackDamage: 34,
    attackEnergy: 12,
    attackCooldown: 1.15,
    metalValue: 210,
    metalCost: 210,
    productionTime: 13,
    supplyCost: 12,
    abilities: {
      overdrive: {
        name: "Overdrive",
        energyCost: 34,
        duration: 6,
        speedMultiplier: 1.65,
        cooldownMultiplier: 0.65,
      },
    },
    provisionalBalance: true,
  },
  assault_mech_t3: {
    name: "Tier 3 Bulwark Mech",
    role: "bulwark",
    tier: 3,
    radius: 13,
    maxHp: 370,
    maxEnergy: 1440,
    speed: 76,
    movementEnergyPerUnit: 0.058,
    attackRange: 180,
    attackDamage: 46,
    attackEnergy: 14,
    attackCooldown: 1.05,
    metalValue: 310,
    metalCost: 310,
    productionTime: 16,
    supplyCost: 16,
    abilities: {
      overdrive: {
        name: "Overdrive",
        energyCost: 40,
        duration: 6,
        speedMultiplier: 1.65,
        cooldownMultiplier: 0.65,
      },
    },
    provisionalBalance: true,
  },
  skyguard_mech: {
    name: "Tier 1 Skyguard Mech",
    role: "anti_air_mech",
    roleDescription: "Anti-air missile defense · 2× damage against aircraft",
    tier: 1,
    radius: 10,
    maxHp: 105,
    maxEnergy: 720,
    speed: 78,
    movementEnergyPerUnit: 0.05,
    attackRange: 190,
    attackDamage: 11,
    attackEnergy: 5,
    attackCooldown: 0.7,
    airDamageMultiplier: 2,
    preferredTargetLayer: "air",
    metalValue: 110,
    metalCost: 110,
    productionTime: 8,
    supplyCost: 5,
    provisionalBalance: true,
  },
  skyguard_mech_t2: {
    name: "Tier 2 Skyguard Mech",
    role: "anti_air_mech",
    roleDescription: "Anti-air missile defense · 2× damage against aircraft",
    tier: 2,
    radius: 11,
    maxHp: 150,
    maxEnergy: 1020,
    speed: 84,
    movementEnergyPerUnit: 0.045,
    attackRange: 215,
    attackDamage: 16,
    attackEnergy: 6,
    attackCooldown: 0.63,
    airDamageMultiplier: 2,
    preferredTargetLayer: "air",
    metalValue: 170,
    metalCost: 170,
    productionTime: 10,
    supplyCost: 8,
    provisionalBalance: true,
  },
  skyguard_mech_t3: {
    name: "Tier 3 Skyguard Mech",
    role: "anti_air_mech",
    roleDescription: "Anti-air missile defense · 2× damage against aircraft",
    tier: 3,
    radius: 12,
    maxHp: 205,
    maxEnergy: 1380,
    speed: 90,
    movementEnergyPerUnit: 0.04,
    attackRange: 245,
    attackDamage: 22,
    attackEnergy: 8,
    attackCooldown: 0.56,
    airDamageMultiplier: 2,
    preferredTargetLayer: "air",
    metalValue: 250,
    metalCost: 250,
    productionTime: 13,
    supplyCost: 11,
    provisionalBalance: true,
  },
  radar_mech: {
    name: "Tier 1 Watchman Mech",
    role: "radar_mech",
    roleDescription: "Long-range radar scout with one light defensive gun",
    tier: 1,
    radius: 9,
    maxHp: 125,
    maxEnergy: 720,
    speed: 82,
    movementEnergyPerUnit: 0.05,
    attackRange: 145,
    attackDamage: 6,
    attackEnergy: 4,
    attackCooldown: 0.8,
    visionRange: 650,
    radarRange: 650,
    metalValue: 115,
    metalCost: 115,
    productionTime: 8,
    supplyCost: 5,
    additionalWeaponHardpoints: 0,
    provisionalBalance: true,
  },
  radar_mech_t2: {
    name: "Tier 2 Watchman Mech",
    role: "radar_mech",
    roleDescription: "Long-range radar scout with one light defensive gun",
    tier: 2,
    radius: 10,
    maxHp: 175,
    maxEnergy: 990,
    speed: 88,
    movementEnergyPerUnit: 0.045,
    attackRange: 165,
    attackDamage: 9,
    attackEnergy: 5,
    attackCooldown: 0.72,
    visionRange: 800,
    radarRange: 800,
    metalValue: 175,
    metalCost: 175,
    productionTime: 10,
    supplyCost: 7,
    additionalWeaponHardpoints: 0,
    provisionalBalance: true,
  },
  radar_mech_t3: {
    name: "Tier 3 Watchman Mech",
    role: "radar_mech",
    roleDescription: "Long-range radar scout with one light defensive gun",
    tier: 3,
    radius: 11,
    maxHp: 240,
    maxEnergy: 1350,
    speed: 94,
    movementEnergyPerUnit: 0.04,
    attackRange: 185,
    attackDamage: 13,
    attackEnergy: 7,
    attackCooldown: 0.64,
    visionRange: 950,
    radarRange: 950,
    metalValue: 260,
    metalCost: 260,
    productionTime: 13,
    supplyCost: 10,
    additionalWeaponHardpoints: 0,
    provisionalBalance: true,
  },
  energy_carrier: {
    name: "Tier 1 Arc Energy Carrier",
    role: "carrier",
    tier: 1,
    radius: 10,
    maxHp: 145,
    maxEnergy: 2520,
    speed: 62,
    movementEnergyPerUnit: 0.04,
    attackRange: 125,
    attackDamage: 5,
    attackEnergy: 4,
    attackCooldown: 0.9,
    metalValue: 120,
    metalCost: 120,
    productionTime: 9,
    supplyCost: 6,
    transferRange: 105,
    transferRate: 35,
    protectedReserve: 70,
    provisionalBalance: true,
  },
  energy_carrier_t2: {
    name: "Tier 2 Arc Energy Carrier",
    role: "carrier",
    tier: 2,
    radius: 11,
    maxHp: 205,
    maxEnergy: 3600,
    speed: 66,
    movementEnergyPerUnit: 0.036,
    attackRange: 140,
    attackDamage: 7,
    attackEnergy: 5,
    attackCooldown: 0.82,
    metalValue: 180,
    metalCost: 180,
    productionTime: 11,
    supplyCost: 9,
    transferRange: 120,
    transferRate: 50,
    protectedReserve: 90,
    provisionalBalance: true,
  },
  energy_carrier_t3: {
    name: "Tier 3 Arc Energy Carrier",
    role: "carrier",
    tier: 3,
    radius: 12,
    maxHp: 285,
    maxEnergy: 5100,
    speed: 70,
    movementEnergyPerUnit: 0.032,
    attackRange: 155,
    attackDamage: 10,
    attackEnergy: 6,
    attackCooldown: 0.74,
    metalValue: 260,
    metalCost: 260,
    productionTime: 14,
    supplyCost: 12,
    transferRange: 140,
    transferRate: 70,
    protectedReserve: 120,
    provisionalBalance: true,
  },
  ...FACTORY_UNIT_DEFINITIONS,
  raider: {
    name: "Hostile Raider",
    role: "raider",
    tier: 1,
    radius: 9,
    maxHp: 105,
    maxEnergy: 1080,
    speed: 108,
    movementEnergyPerUnit: 0.025,
    attackRange: 120,
    attackDamage: 10,
    attackEnergy: 4,
    attackCooldown: 1.1,
    structureDamageMultiplier: 1.75,
    preferredStructureFamilies: Object.freeze([
      "generator",
      "battery",
      "power_tower",
      "charger",
      "metal_mine",
      "salvage_yard",
      "supply_complex",
      "factory",
    ]),
    metalValue: 90,
    metalCost: 90,
    productionTime: 7,
    supplyCost: 4,
    provisionalBalance: true,
  },
};

export const UNIT_DEFINITIONS = Object.freeze(
  Object.fromEntries(
    Object.entries(baseUnitDefinitions).map(([type, definition]) => [
      type,
      Object.freeze({
        ...definition,
        spriteScale: definition.spriteScale ?? (
          definition.unitDomain === "experimental"
            ? 1
            : 1 + Math.max(0, definition.tier - 1) * 0.1
        ),
        additionalWeaponHardpoints: definition.additionalWeaponHardpoints ?? (
          definition.unitDomain !== "experimental" && definition.attackDamage > 0
            ? definition.transferRate
              ? definition.tier
              : Math.max(0, definition.tier - 1)
            : 0
        ),
        visionRange: definition.visionRange ?? Math.max(
          definition.movementLayer === "air" ? 400 : 320,
          (definition.attackRange || definition.automaticTargetAcquisitionRange || 0) + 80,
        ),
        productionTime: definition.productionTime * BUILD_DURATION_MULTIPLIER,
      }),
    ]),
  ),
);

const structureDefinitions = {
  headquarters: {
    name: "Command Headquarters",
    family: "headquarters",
    headquarters: true,
    buildable: false,
    testerSpawnable: false,
    tier: 1,
    radius: 52,
    footprint: [3, 3],
    maxHp: 1800,
    powerRadius: 320,
    generationRate: 20,
    storageCapacity: 240,
    chargeRate: 20,
    dischargeRate: 90,
    metalRate: 4,
    attackRange: 420,
    attackDamage: 8,
    attackEnergy: 4,
    attackCooldown: 1.2,
    capacitorCapacity: 12,
    capacitorChargeRate: 4,
    productionPowerDemand: 6,
    productionRate: 1,
    production: ["worker_drone_t1"],
    metalCost: 0,
    buildTime: 0,
    provisionalBalance: true,
  },
  generator: {
    name: "Pulse Generator",
    family: "generator",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 500,
    powerRadius: 245,
    generationRate: 14,
    storageCapacity: 80,
    chargeRate: 14,
    dischargeRate: 40,
    metalCost: 120,
    buildTime: 8,
    provisionalBalance: true,
  },
  battery: {
    name: "Grid Battery",
    family: "battery",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 380,
    powerRadius: 225,
    storageCapacity: 360,
    chargeRate: 48,
    dischargeRate: 180,
    metalCost: 100,
    buildTime: 7,
    provisionalBalance: true,
  },
  power_tower: {
    name: "Power Relay Tower",
    family: "power_tower",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 270,
    powerDemand: 0.5,
    relayRadius: 245,
    storageCapacity: 30,
    chargeRate: 8,
    dischargeRate: 12,
    metalCost: 55,
    buildTime: 5,
    provisionalBalance: true,
  },
  radar_tower: {
    name: "Tier 1 Radar Array",
    family: "radar_tower",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 320,
    powerDemand: 3,
    visionRange: 950,
    radarRange: 950,
    metalCost: 140,
    buildTime: 9,
    provisionalBalance: true,
  },
  charger: {
    name: "Induction Charger",
    family: "charger",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 360,
    powerDemand: 3,
    chargeRadius: 260,
    chargeRate: 112,
    metalCost: 90,
    buildTime: 7,
    provisionalBalance: true,
  },
  metal_mine: {
    name: "Crystal Harvester",
    family: "metal_mine",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 410,
    powerDemand: 2,
    metalRate: 5,
    requiresDeposit: true,
    metalCost: 110,
    buildTime: 8,
  },
  mech_factory_t1: {
    name: "Tier 1 Mech Factory",
    family: "factory",
    factoryBranch: "mech",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 34,
    footprint: [2, 2],
    maxHp: 650,
    powerDemand: 3,
    productionPowerDemand: 6,
    productionRate: 1,
    tier: 1,
    production: ["worker_drone_t1", "scout_mech", "assault_mech", "skyguard_mech", "energy_carrier", "radar_mech"],
    metalCost: 180,
    buildTime: 12,
  },
  mech_factory_t2: {
    name: "Tier 2 Mech Factory",
    family: "factory",
    factoryBranch: "mech",
    buildTier: 2,
    minimumWorkerTier: 1,
    radius: 52,
    footprint: [3, 3],
    maxHp: 820,
    powerDemand: 5,
    productionPowerDemand: 10,
    productionRate: 1.25,
    tier: 2,
    production: ["worker_drone_t2", "scout_mech_t2", "assault_mech_t2", "skyguard_mech_t2", "energy_carrier_t2", "radar_mech_t2"],
    metalCost: 340,
    buildTime: 18,
  },
  mech_factory_t3: {
    name: "Tier 3 Mech Factory",
    family: "factory",
    factoryBranch: "mech",
    buildTier: 3,
    minimumWorkerTier: 2,
    radius: 72,
    footprint: [4, 4],
    maxHp: 1050,
    powerDemand: 8,
    productionPowerDemand: 16,
    productionRate: 1.5,
    tier: 3,
    production: ["worker_drone_t3", "scout_mech_t3", "assault_mech_t3", "skyguard_mech_t3", "energy_carrier_t3", "radar_mech_t3"],
    metalCost: 600,
    buildTime: 25,
  },
  supply_complex: {
    name: "Strategic Supply Complex",
    family: "supply_complex",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 160,
    footprint: [8, 6],
    maxHp: 2400,
    powerDemand: 6,
    upgradePowerDemand: 6,
    metalCost: 1200,
    buildTime: 40,
    supplyLevels: [
      { capacity: 5000 },
      { capacity: 10000, metalCost: 800, upgradeTime: 25 },
      { capacity: 20000, metalCost: 1600, upgradeTime: 40 },
    ],
    provisionalBalance: true,
  },
  sentry_turret: {
    name: "Sentry Turret",
    family: "sentry_turret",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 390,
    powerDemand: 0,
    attackRange: 185,
    attackDamage: 18,
    attackEnergy: 4,
    attackCooldown: 0.75,
    capacitorCapacity: 16,
    capacitorChargeRate: 11,
    metalCost: 100,
    buildTime: 6,
    provisionalBalance: true,
  },
  shield_turret: {
    name: "Shield Turret",
    family: "shield_turret",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 340,
    powerDemand: 2,
    shieldRadius: 250,
    shieldCapacity: 520,
    shieldRegenRate: 12,
    shieldEnergyPerPoint: 0.75,
    metalCost: 160,
    buildTime: 10,
    provisionalBalance: true,
  },
  mortar_turret: {
    name: "Mortar Turret",
    family: "mortar_turret",
    role: "mortar",
    roleDescription: "Long-range indirect fire with a close-range dead zone",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 340,
    powerDemand: 0,
    minimumAttackRange: 140,
    attackRange: 420,
    attackDamage: 60,
    attackEnergy: 18,
    attackCooldown: 3.2,
    projectileSpeed: 520,
    projectileTracksTarget: true,
    capacitorCapacity: 36,
    capacitorChargeRate: 12,
    metalCost: 165,
    buildTime: 11,
    provisionalBalance: true,
  },
  flak_turret: {
    name: "Flak Turret",
    family: "flak_turret",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 18,
    footprint: [1, 1],
    maxHp: 330,
    powerDemand: 0,
    attackRange: 225,
    attackDamage: 8,
    attackEnergy: 2,
    attackCooldown: 0.38,
    airDamageMultiplier: 2,
    preferredTargetLayer: "air",
    capacitorCapacity: 12,
    capacitorChargeRate: 9,
    metalCost: 95,
    buildTime: 7,
    provisionalBalance: true,
  },
  salvage_yard: {
    name: "Salvage Reclamation Yard",
    family: "salvage_yard",
    buildTier: 1,
    minimumWorkerTier: 1,
    radius: 34,
    footprint: [2, 2],
    maxHp: 430,
    powerDemand: 2,
    droneCount: 3,
    droneReplacementTime: 8,
    metalCost: 150,
    buildTime: 10,
  },
};

Object.assign(structureDefinitions, {
  vehicle_factory_t1: {
    name: "Tier 1 Vehicle Factory", family: "factory", factoryBranch: "vehicle",
    buildTier: 1, minimumWorkerTier: 1, tier: 1, radius: 34, footprint: [2, 2],
    maxHp: 700, powerDemand: 4, productionPowerDemand: 7,
    production: ["scout_vehicle", "battle_tank", "mobile_artillery", "flak_crawler", "grid_tanker", "radar_vehicle"],
    productionRate: 1,
    metalCost: 200, buildTime: 13, provisionalBalance: true,
  },
  generator_t2: {
    ...structureDefinitions.generator, name: "Tier 2 Pulse Generator", buildTier: 2,
    minimumWorkerTier: 2, radius: 34, footprint: [2, 2], maxHp: 750, powerRadius: 285,
    generationRate: 25, storageCapacity: 150, chargeRate: 25, dischargeRate: 70,
    metalCost: 240, buildTime: 14,
  },
  battery_t2: {
    ...structureDefinitions.battery, name: "Tier 2 Grid Battery", buildTier: 2,
    minimumWorkerTier: 2, radius: 34, footprint: [2, 2], maxHp: 570, powerRadius: 260,
    storageCapacity: 650, chargeRate: 80, dischargeRate: 280, metalCost: 190, buildTime: 12,
  },
  power_tower_t2: {
    ...structureDefinitions.power_tower, name: "Tier 2 Power Relay Tower", buildTier: 2,
    minimumWorkerTier: 2, radius: 18, footprint: [1, 1], maxHp: 400, powerDemand: 0.75, relayRadius: 285,
    storageCapacity: 55, chargeRate: 14, dischargeRate: 22, metalCost: 100, buildTime: 8,
  },
  radar_tower_t2: {
    ...structureDefinitions.radar_tower, name: "Tier 2 Radar Array", buildTier: 2,
    minimumWorkerTier: 2, radius: 28, footprint: [2, 2], maxHp: 510, powerDemand: 5,
    visionRange: 1250, radarRange: 1250, metalCost: 270, buildTime: 15,
  },
  charger_t2: {
    ...structureDefinitions.charger, name: "Tier 2 Induction Charger", buildTier: 2,
    minimumWorkerTier: 2, radius: 34, footprint: [2, 2], maxHp: 540, powerDemand: 5,
    chargeRadius: 310, chargeRate: 170, metalCost: 175, buildTime: 12,
  },
  metal_mine_t2: {
    ...structureDefinitions.metal_mine, name: "Tier 2 Crystal Harvester", buildTier: 2,
    minimumWorkerTier: 2, radius: 34, footprint: [2, 2], maxHp: 620, powerDemand: 3,
    metalRate: 8, metalCost: 210, buildTime: 13, provisionalBalance: true,
  },
  mech_factory_t2: structureDefinitions.mech_factory_t2,
  vehicle_factory_t2: {
    name: "Tier 2 Vehicle Factory", family: "factory", factoryBranch: "vehicle",
    buildTier: 2, minimumWorkerTier: 2, tier: 2, radius: 52, footprint: [3, 3],
    maxHp: 900, powerDemand: 7, productionPowerDemand: 12,
    production: ["scout_vehicle_t2", "battle_tank_t2", "mobile_artillery_t2", "flak_crawler_t2", "grid_tanker_t2", "radar_vehicle_t2"],
    productionRate: 1.25,
    metalCost: 380, buildTime: 20, provisionalBalance: true,
  },
  air_factory_t2: {
    name: "Tier 2 Air Factory", family: "factory", factoryBranch: "air",
    buildTier: 2, minimumWorkerTier: 2, tier: 2, radius: 52, footprint: [3, 3],
    maxHp: 810, powerDemand: 8, productionPowerDemand: 14,
    production: ["interceptor_t2", "gunship_t2", "bomber_t2", "energy_tender_t2", "radar_aircraft_t2", "dropship_t2"],
    productionRate: 1.25,
    metalCost: 420, buildTime: 21, provisionalBalance: true,
  },
  sentry_turret_t2: {
    ...structureDefinitions.sentry_turret, name: "Tier 2 Sentry Turret", buildTier: 2,
    minimumWorkerTier: 2, radius: 28, footprint: [2, 2], maxHp: 620, attackRange: 265, attackDamage: 34,
    attackEnergy: 7, attackCooldown: 0.68, capacitorCapacity: 35, capacitorChargeRate: 24,
    metalCost: 190, buildTime: 10, provisionalBalance: true,
  },
  shield_turret_t2: {
    ...structureDefinitions.shield_turret, name: "Tier 2 Shield Turret", buildTier: 2,
    minimumWorkerTier: 2, radius: 28, footprint: [2, 2], maxHp: 560, powerDemand: 4,
    shieldRadius: 355, shieldCapacity: 1050, shieldRegenRate: 22,
    metalCost: 310, buildTime: 16, provisionalBalance: true,
  },
  mortar_turret_t2: {
    ...structureDefinitions.mortar_turret, name: "Tier 2 Mortar Turret", buildTier: 2,
    minimumWorkerTier: 2, radius: 28, footprint: [2, 2], maxHp: 520,
    minimumAttackRange: 160, attackRange: 550, attackDamage: 100,
    attackEnergy: 28, attackCooldown: 2.8, capacitorCapacity: 70, capacitorChargeRate: 25,
    metalCost: 310, buildTime: 16, provisionalBalance: true,
  },
  flak_turret_t2: {
    ...structureDefinitions.flak_turret, name: "Tier 2 Flak Turret", buildTier: 2,
    minimumWorkerTier: 2, radius: 28, footprint: [2, 2], maxHp: 480,
    attackRange: 285, attackDamage: 13, attackEnergy: 3.5, attackCooldown: 0.32,
    capacitorCapacity: 24, capacitorChargeRate: 18,
    metalCost: 175, buildTime: 11, provisionalBalance: true,
  },
  salvage_yard_t2: {
    ...structureDefinitions.salvage_yard, name: "Tier 2 Salvage Reclamation Yard", buildTier: 2,
    minimumWorkerTier: 2, radius: 52, footprint: [3, 3], maxHp: 620, powerDemand: 3,
    droneCount: 4, droneReplacementTime: 7, metalCost: 280, buildTime: 16,
    provisionalBalance: true,
  },
  generator_t3: {
    ...structureDefinitions.generator, name: "Tier 3 Pulse Generator", buildTier: 3,
    minimumWorkerTier: 3, radius: 34, footprint: [2, 2], maxHp: 1100, powerRadius: 330,
    generationRate: 45, storageCapacity: 280, chargeRate: 45, dischargeRate: 120,
    metalCost: 480, buildTime: 22,
  },
  battery_t3: {
    ...structureDefinitions.battery, name: "Tier 3 Grid Battery", buildTier: 3,
    minimumWorkerTier: 3, radius: 34, footprint: [2, 2], maxHp: 840, powerRadius: 300,
    storageCapacity: 1100, chargeRate: 130, dischargeRate: 430, metalCost: 360, buildTime: 19,
  },
  power_tower_t3: {
    ...structureDefinitions.power_tower, name: "Tier 3 Power Relay Tower", buildTier: 3,
    minimumWorkerTier: 3, radius: 18, footprint: [1, 1], maxHp: 590, powerDemand: 1,
    relayRadius: 330, storageCapacity: 100, chargeRate: 24, dischargeRate: 38,
    metalCost: 180, buildTime: 12,
  },
  radar_tower_t3: {
    ...structureDefinitions.radar_tower, name: "Tier 3 Radar Array", buildTier: 3,
    minimumWorkerTier: 3, radius: 28, footprint: [2, 2], maxHp: 760, powerDemand: 8,
    visionRange: 1600, radarRange: 1600, metalCost: 500, buildTime: 23,
  },
  charger_t3: {
    ...structureDefinitions.charger, name: "Tier 3 Induction Charger", buildTier: 3,
    minimumWorkerTier: 3, radius: 34, footprint: [2, 2], maxHp: 800, powerDemand: 8,
    chargeRadius: 360, chargeRate: 250, metalCost: 330, buildTime: 19,
  },
  metal_mine_t3: {
    ...structureDefinitions.metal_mine, name: "Tier 3 Crystal Harvester", buildTier: 3,
    minimumWorkerTier: 3, radius: 34, footprint: [2, 2], maxHp: 900, powerDemand: 5,
    metalRate: 12, metalCost: 390, buildTime: 20, provisionalBalance: true,
  },
  mech_factory_t3: structureDefinitions.mech_factory_t3,
  vehicle_factory_t3: {
    name: "Tier 3 Vehicle Factory", family: "factory", factoryBranch: "vehicle",
    buildTier: 3, minimumWorkerTier: 3, tier: 3, radius: 72, footprint: [4, 4],
    maxHp: 1180, powerDemand: 11, productionPowerDemand: 19,
    production: ["scout_vehicle_t3", "battle_tank_t3", "mobile_artillery_t3", "flak_crawler_t3", "grid_tanker_t3", "radar_vehicle_t3"],
    productionRate: 1.5,
    metalCost: 680, buildTime: 28, provisionalBalance: true,
  },
  air_factory_t3: {
    name: "Tier 3 Air Factory", family: "factory", factoryBranch: "air",
    buildTier: 3, minimumWorkerTier: 3, tier: 3, radius: 72, footprint: [4, 4],
    maxHp: 1050, powerDemand: 13, productionPowerDemand: 22,
    production: ["interceptor_t3", "gunship_t3", "bomber_t3", "energy_tender_t3", "radar_aircraft_t3", "dropship_t3"],
    productionRate: 1.5,
    metalCost: 740, buildTime: 30, provisionalBalance: true,
  },
  sentry_turret_t3: {
    ...structureDefinitions.sentry_turret, name: "Tier 3 Sentry Turret", buildTier: 3,
    minimumWorkerTier: 3, radius: 28, footprint: [2, 2], maxHp: 900, attackRange: 360,
    attackDamage: 60, attackEnergy: 12, attackCooldown: 0.55, capacitorCapacity: 72,
    capacitorChargeRate: 44,
    metalCost: 360, buildTime: 16, provisionalBalance: true,
  },
  shield_turret_t3: {
    ...structureDefinitions.shield_turret, name: "Tier 3 Shield Turret", buildTier: 3,
    minimumWorkerTier: 3, radius: 28, footprint: [2, 2], maxHp: 820, powerDemand: 7,
    shieldRadius: 480, shieldCapacity: 1900, shieldRegenRate: 36,
    metalCost: 560, buildTime: 24, provisionalBalance: true,
  },
  mortar_turret_t3: {
    ...structureDefinitions.mortar_turret, name: "Tier 3 Mortar Turret", buildTier: 3,
    minimumWorkerTier: 3, radius: 28, footprint: [2, 2], maxHp: 780,
    minimumAttackRange: 180, attackRange: 700, attackDamage: 165,
    attackEnergy: 42, attackCooldown: 2.4, capacitorCapacity: 126, capacitorChargeRate: 48,
    metalCost: 560, buildTime: 23, provisionalBalance: true,
  },
  flak_turret_t3: {
    ...structureDefinitions.flak_turret, name: "Tier 3 Flak Turret", buildTier: 3,
    minimumWorkerTier: 3, radius: 28, footprint: [2, 2], maxHp: 690,
    attackRange: 360, attackDamage: 20, attackEnergy: 5, attackCooldown: 0.27,
    capacitorCapacity: 42, capacitorChargeRate: 30,
    metalCost: 320, buildTime: 17, provisionalBalance: true,
  },
  salvage_yard_t3: {
    ...structureDefinitions.salvage_yard, name: "Tier 3 Salvage Reclamation Yard", buildTier: 3,
    minimumWorkerTier: 3, radius: 52, footprint: [3, 3], maxHp: 900, powerDemand: 5,
    droneCount: 5, droneReplacementTime: 6, metalCost: 500, buildTime: 24,
    provisionalBalance: true,
  },
  experimental_factory: {
    name: "Experimental Factory", family: "factory", factoryBranch: "experimental",
    buildTier: 3, minimumWorkerTier: 3, tier: 3, radius: 90, footprint: [5, 5],
    maxHp: 1500, powerDemand: 18, productionPowerDemand: 30,
    production: ["arsenal_colossus", "hexapod_landship", "zenith_doughnut"],
    metalCost: 1000, buildTime: 36, provisionalBalance: true,
  },
});

for (const [type, definition] of Object.entries(structureDefinitions)) {
  structureDefinitions[type] = Object.freeze({
    ...definition,
    visionRange: definition.visionRange ?? Math.max(340, (definition.attackRange || 0) + 80),
    buildTime: definition.buildTime * BUILD_DURATION_MULTIPLIER,
  });
}

export const STRUCTURE_DEFINITIONS = Object.freeze(structureDefinitions);

export const BUILD_MENU_BY_TIER = Object.freeze({
  1: Object.freeze([
    "generator", "battery", "power_tower", "radar_tower", "charger", "metal_mine",
    "mech_factory_t1", "vehicle_factory_t1",
    "sentry_turret", "shield_turret", "mortar_turret", "flak_turret", "salvage_yard", "supply_complex",
  ]),
  2: Object.freeze([
    "generator_t2", "battery_t2", "power_tower_t2", "radar_tower_t2", "charger_t2", "metal_mine_t2",
    "mech_factory_t2", "vehicle_factory_t2", "air_factory_t2",
    "sentry_turret_t2", "shield_turret_t2", "mortar_turret_t2", "flak_turret_t2", "salvage_yard_t2",
  ]),
  3: Object.freeze([
    "generator_t3", "battery_t3", "power_tower_t3", "radar_tower_t3", "charger_t3", "metal_mine_t3",
    "mech_factory_t3", "vehicle_factory_t3", "air_factory_t3",
    "sentry_turret_t3", "shield_turret_t3", "mortar_turret_t3", "flak_turret_t3", "salvage_yard_t3",
    "experimental_factory",
  ]),
});

export const BUILD_MENU = Object.freeze(Object.values(BUILD_MENU_BY_TIER).flat());

export function canWorkerTierBuildStructure(workerTier, structureType) {
  const definition = STRUCTURE_DEFINITIONS[structureType];
  return Boolean(
    definition &&
    definition.buildable !== false &&
    workerTier >= (definition.minimumWorkerTier || definition.buildTier || 1),
  );
}

export function getNextStructureTierType(structureType) {
  const definition = STRUCTURE_DEFINITIONS[structureType];
  if (!definition) return null;
  const nextTier = (definition.buildTier || definition.tier || 1) + 1;
  const match = Object.entries(STRUCTURE_DEFINITIONS).find(([, candidate]) => {
    if ((candidate.buildTier || candidate.tier || 1) !== nextTier) return false;
    if (candidate.family !== definition.family) return false;
    if (definition.family !== "factory") return true;
    return candidate.factoryBranch === definition.factoryBranch;
  });
  return match?.[0] || null;
}

export function getNextWorkerTierType(unitType) {
  const definition = UNIT_DEFINITIONS[unitType];
  if (!definition?.workerTier) return null;
  const nextTier = definition.workerTier + 1;
  const match = Object.entries(UNIT_DEFINITIONS).find(
    ([, candidate]) => candidate.workerTier === nextTier,
  );
  return match?.[0] || null;
}

export const DRONE_DEFINITION = Object.freeze({
  name: "Reclamation Drone",
  radius: 5,
  maxHp: 35,
  speed: 130,
  visionRange: 300,
  terrainOverflightTypes: Object.freeze(["starting_wall"]),
  carryCapacity: 24,
  collectionRate: 8,
});

export const SIMULATION_RULES = Object.freeze({
  baseSupplyCapacity: 1000,
  unitTesterResourceAmount: 1_000_000_000,
  normalAirDamageMultiplier: 0.55,
  stasisRegenerationRate: 2.5,
  lowEnergyRegenerationRate: 1.5,
  reactivationThreshold: 18,
  lowEnergyRatio: 0.2,
  structureCollisionPadding: 0,
  unitCollisionPadding: 2,
  rallyFormationSpacing: 32,
  wreckMergeRadius: 80,
  buildingGridSize: 40,
  constructionStartingHpRatio: 0.1,
  constructionCancelRefundRate: 0.75,
  workerProductionAssistRange: 24,
  automaticTargetScanInterval: 0.2,
  staticDefenseTargetScanInterval: 0.1,
  productionAssistPowerDemandRatioStart: 0.2,
  productionAssistPowerDemandRatioStep: 0.01,
  enemyInitialThinkDelay: 1,
  enemyThinkInterval: 1,
  enemyAttackWaveSize: 3,
  enemyMinimumFreeWorkers: 1,
  enemyMaxProductionAssistantsPerFactory: 2,
  enemyMaxMobileEnergySupport: 3,
  enemyCombatUnitsPerMobileEnergySupport: 8,
  enemyAssaultTargetEvaluationLimit: 64,
  enemyDifficultyProfiles: Object.freeze({
    easy: Object.freeze({ thinkInterval: 1.8, initialThinkDelay: 1.8, attackWaveSize: 5 }),
    medium: Object.freeze({ thinkInterval: 1, initialThinkDelay: 1, attackWaveSize: 3 }),
    hard: Object.freeze({ thinkInterval: 0.55, initialThinkDelay: 0.55, attackWaveSize: 3 }),
  }),
  enemyRushResponseRadius: 800,
  enemyConstructionThreatRadius: 360,
  enemyConstructionSafetyStrengthRatio: 1,
  enemyConstructionLossRadius: 280,
  enemyConstructionLossMemoryDuration: 60,
  enemyConstructionRecentBuildWindow: 30,
  enemyConstructionLossMemoryLimit: 12,
  enemySupplyLowRatio: 0.1,
  enemyChargerDemandEnergyRatio: 0.5,
  enemyChargerReleaseEnergyRatio: 0.9,
  enemyChargerMinimumDemandUnits: 2,
  enemyChargerStagingRadius: 520,
  enemyGenerationReserveRatio: 0.2,
  enemyPowerConsumersPerGenerator: 4,
  enemyLowMetalThreshold: 400,
  enemyStructureUpgradeMetalReserve: 400,
  enemyExpansionSurplusMetal: 900,
  enemyTierTwoMineCount: 2,
  enemyTierThreeMineCount: 3,
  enemyExpansionInterval: 55,
  enemyFortifiedExpansionBonus: 1,
  enemyOutpostDistance: 480,
  enemyOutpostDefenseRadius: 300,
  enemyOutpostGarrisonSize: 2,
  enemyOutpostGarrisonLeash: 180,
  enemyOutpostResponseRadius: 520,
  enemyHeavyDefenseCount: 3,
  enemyHeavyDefenseRadius: 420,
  enemyAssaultEvaluationRadius: 520,
  enemyAssaultSafetyStrengthRatio: 1.5,
});

export function gridCoverageBounds(x, y, reach) {
  if (!Number.isFinite(reach) || reach <= 0) return null;
  const gridSize = SIMULATION_RULES.buildingGridSize;
  const halfCell = gridSize / 2;
  const minimumColumn = Math.ceil((x - reach - halfCell) / gridSize);
  const maximumColumn = Math.floor((x + reach - halfCell) / gridSize);
  const minimumRow = Math.ceil((y - reach - halfCell) / gridSize);
  const maximumRow = Math.floor((y + reach - halfCell) / gridSize);
  const left = minimumColumn * gridSize;
  const right = (maximumColumn + 1) * gridSize;
  const top = minimumRow * gridSize;
  const bottom = (maximumRow + 1) * gridSize;
  return {
    left,
    right,
    top,
    bottom,
    width: right - left,
    height: bottom - top,
    columns: maximumColumn - minimumColumn + 1,
    rows: maximumRow - minimumRow + 1,
  };
}

export function powerCoverageBounds(structureType, x, y) {
  const definition = STRUCTURE_DEFINITIONS[structureType];
  const reach = definition?.relayRadius || definition?.powerRadius || 0;
  return gridCoverageBounds(x, y, reach);
}

export function pointInGridCoverage(bounds, x, y) {
  return Boolean(
    bounds &&
    x >= bounds.left &&
    x < bounds.right &&
    y >= bounds.top &&
    y < bounds.bottom
  );
}

export function structureFootprint(structureType) {
  const definition = STRUCTURE_DEFINITIONS[structureType];
  const [columns = 1, rows = 1] = definition?.footprint || [];
  const width = columns * SIMULATION_RULES.buildingGridSize;
  const height = rows * SIMULATION_RULES.buildingGridSize;
  return {
    columns,
    rows,
    width,
    height,
    halfWidth: width / 2,
    halfHeight: height / 2,
  };
}
