export const WORLD_WIDTH = 3200;
export const WORLD_HEIGHT = 1800;

export const UNIT_DEFINITIONS = Object.freeze({
  worker_drone_t1: {
    name: "Tier 1 Worker Drone",
    role: "worker",
    tier: 1,
    radius: 6,
    maxHp: 70,
    maxEnergy: 690,
    speed: 72,
    movementEnergyPerUnit: 0.035,
    attackRange: 0,
    attackDamage: 0,
    attackEnergy: 0,
    attackCooldown: 0,
    metalValue: 45,
    metalCost: 45,
    productionTime: 5,
    supplyCost: 1,
    workerTier: 1,
    buildRate: 1,
  },
  worker_drone_t2: {
    name: "Tier 2 Worker Drone",
    role: "worker",
    tier: 2,
    radius: 7,
    maxHp: 95,
    maxEnergy: 990,
    speed: 78,
    movementEnergyPerUnit: 0.03,
    attackRange: 0,
    attackDamage: 0,
    attackEnergy: 0,
    attackCooldown: 0,
    metalValue: 75,
    metalCost: 75,
    productionTime: 5,
    supplyCost: 2,
    workerTier: 2,
    buildRate: 1.65,
  },
  worker_drone_t3: {
    name: "Tier 3 Worker Drone",
    role: "worker",
    tier: 3,
    radius: 8,
    maxHp: 125,
    maxEnergy: 1380,
    speed: 84,
    movementEnergyPerUnit: 0.026,
    attackRange: 0,
    attackDamage: 0,
    attackEnergy: 0,
    attackCooldown: 0,
    metalValue: 120,
    metalCost: 120,
    productionTime: 5,
    supplyCost: 3,
    workerTier: 3,
    buildRate: 2.6,
  },
  scout_mech: {
    name: "Tier 1 Vanguard Mech",
    role: "vanguard",
    tier: 1,
    radius: 9,
    maxHp: 120,
    maxEnergy: 600,
    speed: 92,
    movementEnergyPerUnit: 0.055,
    attackRange: 125,
    attackDamage: 13,
    attackEnergy: 6,
    attackCooldown: 0.8,
    metalValue: 85,
    metalCost: 85,
    productionTime: 7,
    supplyCost: 4,
    provisionalBalance: true,
  },
  scout_mech_t2: {
    name: "Tier 2 Vanguard Mech",
    role: "vanguard",
    tier: 2,
    radius: 10,
    maxHp: 165,
    maxEnergy: 870,
    speed: 98,
    movementEnergyPerUnit: 0.05,
    attackRange: 135,
    attackDamage: 18,
    attackEnergy: 7,
    attackCooldown: 0.72,
    metalValue: 130,
    metalCost: 130,
    productionTime: 8.5,
    supplyCost: 6,
    provisionalBalance: true,
  },
  scout_mech_t3: {
    name: "Tier 3 Vanguard Mech",
    role: "vanguard",
    tier: 3,
    radius: 11,
    maxHp: 220,
    maxEnergy: 1200,
    speed: 105,
    movementEnergyPerUnit: 0.045,
    attackRange: 145,
    attackDamage: 24,
    attackEnergy: 8,
    attackCooldown: 0.64,
    metalValue: 190,
    metalCost: 190,
    productionTime: 10,
    supplyCost: 8,
    provisionalBalance: true,
  },
  assault_mech: {
    name: "Tier 1 Bulwark Mech",
    role: "bulwark",
    tier: 1,
    radius: 11,
    maxHp: 190,
    maxEnergy: 780,
    speed: 68,
    movementEnergyPerUnit: 0.07,
    attackRange: 150,
    attackDamage: 24,
    attackEnergy: 10,
    attackCooldown: 1.25,
    metalValue: 140,
    metalCost: 140,
    productionTime: 11,
    supplyCost: 8,
    abilities: {
      overdrive: {
        name: "Overdrive",
        energyCost: 30,
        duration: 6,
        speedMultiplier: 1.65,
        cooldownMultiplier: 0.65,
      },
    },
    provisionalBalance: true,
  },
  assault_mech_t2: {
    name: "Tier 2 Bulwark Mech",
    role: "bulwark",
    tier: 2,
    radius: 12,
    maxHp: 270,
    maxEnergy: 1080,
    speed: 72,
    movementEnergyPerUnit: 0.064,
    attackRange: 165,
    attackDamage: 34,
    attackEnergy: 12,
    attackCooldown: 1.15,
    metalValue: 210,
    metalCost: 210,
    productionTime: 13,
    supplyCost: 12,
    abilities: {
      overdrive: {
        name: "Overdrive",
        energyCost: 34,
        duration: 6,
        speedMultiplier: 1.65,
        cooldownMultiplier: 0.65,
      },
    },
    provisionalBalance: true,
  },
  assault_mech_t3: {
    name: "Tier 3 Bulwark Mech",
    role: "bulwark",
    tier: 3,
    radius: 13,
    maxHp: 370,
    maxEnergy: 1440,
    speed: 76,
    movementEnergyPerUnit: 0.058,
    attackRange: 180,
    attackDamage: 46,
    attackEnergy: 14,
    attackCooldown: 1.05,
    metalValue: 310,
    metalCost: 310,
    productionTime: 16,
    supplyCost: 16,
    abilities: {
      overdrive: {
        name: "Overdrive",
        energyCost: 40,
        duration: 6,
        speedMultiplier: 1.65,
        cooldownMultiplier: 0.65,
      },
    },
    provisionalBalance: true,
  },
  energy_carrier: {
    name: "Tier 1 Arc Energy Carrier",
    role: "carrier",
    tier: 1,
    radius: 10,
    maxHp: 145,
    maxEnergy: 2520,
    speed: 62,
    movementEnergyPerUnit: 0.04,
    attackRange: 0,
    attackDamage: 0,
    attackEnergy: 0,
    attackCooldown: 0,
    metalValue: 120,
    metalCost: 120,
    productionTime: 9,
    supplyCost: 6,
    transferRange: 105,
    transferRate: 35,
    protectedReserve: 70,
    provisionalBalance: true,
  },
  energy_carrier_t2: {
    name: "Tier 2 Arc Energy Carrier",
    role: "carrier",
    tier: 2,
    radius: 11,
    maxHp: 205,
    maxEnergy: 3600,
    speed: 66,
    movementEnergyPerUnit: 0.036,
    attackRange: 0,
    attackDamage: 0,
    attackEnergy: 0,
    attackCooldown: 0,
    metalValue: 180,
    metalCost: 180,
    productionTime: 11,
    supplyCost: 9,
    transferRange: 120,
    transferRate: 50,
    protectedReserve: 90,
    provisionalBalance: true,
  },
  energy_carrier_t3: {
    name: "Tier 3 Arc Energy Carrier",
    role: "carrier",
    tier: 3,
    radius: 12,
    maxHp: 285,
    maxEnergy: 5100,
    speed: 70,
    movementEnergyPerUnit: 0.032,
    attackRange: 0,
    attackDamage: 0,
    attackEnergy: 0,
    attackCooldown: 0,
    metalValue: 260,
    metalCost: 260,
    productionTime: 14,
    supplyCost: 12,
    transferRange: 140,
    transferRate: 70,
    protectedReserve: 120,
    provisionalBalance: true,
  },
  raider: {
    name: "Hostile Raider",
    role: "raider",
    tier: 1,
    radius: 9,
    maxHp: 135,
    maxEnergy: 1080,
    speed: 54,
    movementEnergyPerUnit: 0.025,
    attackRange: 120,
    attackDamage: 10,
    attackEnergy: 4,
    attackCooldown: 1.1,
    metalValue: 90,
    metalCost: 90,
    productionTime: 7,
    supplyCost: 4,
  },
});

export const STRUCTURE_DEFINITIONS = Object.freeze({
  generator: {
    name: "Pulse Generator",
    radius: 34,
    footprint: [2, 2],
    maxHp: 500,
    powerRadius: 245,
    generationRate: 14,
    storageCapacity: 80,
    chargeRate: 14,
    dischargeRate: 40,
    metalCost: 120,
    buildTime: 8,
    provisionalBalance: true,
  },
  battery: {
    name: "Grid Battery",
    radius: 30,
    footprint: [2, 2],
    maxHp: 380,
    powerRadius: 225,
    storageCapacity: 360,
    chargeRate: 48,
    dischargeRate: 180,
    metalCost: 100,
    buildTime: 7,
    provisionalBalance: true,
  },
  power_tower: {
    name: "Power Relay Tower",
    radius: 18,
    footprint: [1, 1],
    maxHp: 270,
    powerDemand: 0.5,
    relayRadius: 245,
    storageCapacity: 30,
    chargeRate: 8,
    dischargeRate: 12,
    metalCost: 55,
    buildTime: 5,
    provisionalBalance: true,
  },
  charger: {
    name: "Induction Charger",
    radius: 31,
    footprint: [2, 2],
    maxHp: 360,
    powerDemand: 3,
    chargeRadius: 260,
    chargeRate: 112,
    metalCost: 90,
    buildTime: 7,
    provisionalBalance: true,
  },
  metal_mine: {
    name: "Metal Mine",
    radius: 34,
    footprint: [2, 2],
    maxHp: 410,
    powerDemand: 2,
    metalRate: 5,
    metalCost: 110,
    buildTime: 8,
  },
  mech_factory_t1: {
    name: "Tier 1 Mech Factory",
    radius: 60,
    footprint: [3, 2],
    maxHp: 650,
    powerDemand: 3,
    productionPowerDemand: 6,
    tier: 1,
    production: ["worker_drone_t1", "scout_mech", "assault_mech", "energy_carrier"],
    metalCost: 180,
    buildTime: 12,
  },
  mech_factory_t2: {
    name: "Tier 2 Mech Factory",
    radius: 80,
    footprint: [4, 3],
    maxHp: 820,
    powerDemand: 5,
    productionPowerDemand: 10,
    tier: 2,
    production: ["worker_drone_t2", "scout_mech_t2", "assault_mech_t2", "energy_carrier_t2"],
    metalCost: 340,
    buildTime: 18,
  },
  mech_factory_t3: {
    name: "Tier 3 Mech Factory",
    radius: 100,
    footprint: [5, 4],
    maxHp: 1050,
    powerDemand: 8,
    productionPowerDemand: 16,
    tier: 3,
    production: ["worker_drone_t3", "scout_mech_t3", "assault_mech_t3", "energy_carrier_t3"],
    metalCost: 600,
    buildTime: 25,
  },
  supply_complex: {
    name: "Strategic Supply Complex",
    radius: 160,
    footprint: [8, 6],
    maxHp: 2400,
    powerDemand: 6,
    upgradePowerDemand: 6,
    metalCost: 1200,
    buildTime: 40,
    supplyLevels: [
      { capacity: 5000 },
      { capacity: 10000, metalCost: 800, upgradeTime: 25 },
      { capacity: 20000, metalCost: 1600, upgradeTime: 40 },
    ],
    provisionalBalance: true,
  },
  sentry_turret: {
    name: "Sentry Turret",
    radius: 18,
    footprint: [1, 1],
    maxHp: 390,
    powerDemand: 0,
    attackRange: 185,
    attackDamage: 12,
    attackEnergy: 3,
    attackCooldown: 0.85,
    capacitorCapacity: 12,
    capacitorChargeRate: 8,
    metalCost: 85,
    buildTime: 6,
  },
  salvage_yard: {
    name: "Salvage Reclamation Yard",
    radius: 60,
    footprint: [3, 2],
    maxHp: 430,
    powerDemand: 2,
    droneCount: 3,
    droneReplacementTime: 8,
    metalCost: 150,
    buildTime: 10,
  },
});

export const BUILD_MENU = Object.freeze([
  "generator",
  "battery",
  "power_tower",
  "charger",
  "metal_mine",
  "mech_factory_t1",
  "mech_factory_t2",
  "mech_factory_t3",
  "supply_complex",
  "sentry_turret",
  "salvage_yard",
]);

export const DRONE_DEFINITION = Object.freeze({
  name: "Reclamation Drone",
  radius: 5,
  maxHp: 35,
  speed: 85,
  carryCapacity: 24,
  collectionRate: 8,
});

export const SIMULATION_RULES = Object.freeze({
  baseSupplyCapacity: 1000,
  stasisRegenerationRate: 2.5,
  lowEnergyRegenerationRate: 1.5,
  lowEnergyRegenerationThreshold: 18,
  reactivationThreshold: 18,
  lowEnergyRatio: 0.2,
  structureCollisionPadding: 3,
  unitCollisionPadding: 2,
  rallyFormationSpacing: 32,
  buildingGridSize: 40,
  constructionCancelRefundRate: 0.75,
  enemyAttackWaveSize: 4,
});

export function structureFootprint(structureType) {
  const definition = STRUCTURE_DEFINITIONS[structureType];
  const [columns = 1, rows = 1] = definition?.footprint || [];
  const width = columns * SIMULATION_RULES.buildingGridSize;
  const height = rows * SIMULATION_RULES.buildingGridSize;
  return {
    columns,
    rows,
    width,
    height,
    halfWidth: width / 2,
    halfHeight: height / 2,
  };
}
